server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# Koneksi Database MySQL ke Laragon (Port Default 3306)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/db_smart_community?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
